PR feedback

diff --git a/.github/workflows/publish-packages.yml b/.github/workflows/publish-packages.yml
--- a/.github/workflows/publish-packages.yml
+++ b/.github/workflows/publish-packages.yml
@@ -114,7 +114,7 @@ jobs:
           echo "==> Pushing changes to GitHub"
           if [ "$(git current-branch)" = "main" ]; then
             if !git push origin main; then
-                echo "WARNING: Could not push this branch to GitHub!" >&2
+                echo "ERROR: Could not push this branch to GitHub!" >&2
                 echo "Please manually fix that now, before writing the release notes!" >&2
                 exit 2
             else
