publish-python.yml: Add a commit step for version bumps and add a step to create a release tag upon successful publishing.

diff --git a/.github/workflows/publish-python.yml b/.github/workflows/publish-python.yml
--- a/.github/workflows/publish-python.yml
+++ b/.github/workflows/publish-python.yml
@@ -11,17 +11,34 @@ on:
 jobs:
   publish:
     runs-on: ubuntu-latest
+
+    permissions:
+      contents: write
+
     steps:
       - uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.RELEASE_COMMIT_WRITE_TOKEN }}
 
       - name: Install uv
         uses: astral-sh/setup-uv@v5
 
+      - name: Setup git config
+        run: |
+          git config user.name "GitHub Actions Bot"
+          git config user.email "<>"
+
       - name: Set version
         working-directory: packages/liveblocks-python
-        run:
-          sed -i "s/^version = .*/version = \"${{ inputs.version }}\"/"
-          pyproject.toml
+        run: |
+          sed -i "s/^version = .*/version = \"${{ inputs.version }}\"/" pyproject.toml
+          sed -i "s/^package_version_override: .*/package_version_override: ${{ inputs.version }}/" config.yaml
+
+      - name: Commit version bump
+        working-directory: packages/liveblocks-python
+        run: |
+          git add pyproject.toml config.yaml
+          git commit -m "Bump liveblocks-python to ${{ inputs.version }}"
 
       - name: Build and publish
         working-directory: packages/liveblocks-python
@@ -30,3 +47,18 @@ jobs:
         run: |
           uv build
           uv publish
+
+      - name: Create release tag
+        env:
+          VERSION: ${{ inputs.version }}
+          GIT_TAG: v${{ inputs.version }}
+          GITHUB_URL: "https://github.com/liveblocks/liveblocks"
+        run: |
+          if [ "$(git branch --show-current)" = "main" ]; then
+            if ! git push origin main; then
+              echo "ERROR: Could not push to main!" >&2
+              exit 2
+            fi
+          fi
+          git tag "$GIT_TAG" -m "Release $GIT_TAG (python)"
+          git push origin "$GIT_TAG"
