`err` util not available here

diff --git a/.github/workflows/publish-packages.yml b/.github/workflows/publish-packages.yml
--- a/.github/workflows/publish-packages.yml
+++ b/.github/workflows/publish-packages.yml
@@ -114,8 +114,8 @@ jobs:
           echo "==> Pushing changes to GitHub"
           if [ "$(git current-branch)" = "main" ]; then
             if !git push origin main; then
-                err "WARNING: Could not push this branch to GitHub!"
-                err "Please manually fix that now, before writing the release notes!"
+                echo "WARNING: Could not push this branch to GitHub!" >&2
+                echo "Please manually fix that now, before writing the release notes!" >&2
                 exit 2
             else
                 echo "Done! Please finish it off by writing a nice changelog entry on GitHub."
