Only push newly created Git commit with the version bump when on main
On branches/PRs this just causes needless noise. I found myself always
reverting this commit immediately after publishing a new version, to
avoid merge conflicts and PR noise.

diff --git a/.github/workflows/publish-packages.yml b/.github/workflows/publish-packages.yml
--- a/.github/workflows/publish-packages.yml
+++ b/.github/workflows/publish-packages.yml
@@ -111,6 +111,16 @@ jobs:
           GIT_TAG: ${{ inputs.tag }}
           GITHUB_URL: "https://github.com/liveblocks/liveblocks"
         run: |
+          echo "==> Pushing changes to GitHub"
+          if [ "$(git current-branch)" = "main" ]; then
+            if !git push origin main; then
+                err "WARNING: Could not push this branch to GitHub!"
+                err "Please manually fix that now, before writing the release notes!"
+                exit 2
+            else
+                echo "Done! Please finish it off by writing a nice changelog entry on GitHub."
+            fi
+          fi
           git tag "$GIT_TAG" -m "Release $GIT_TAG"
           git push origin "$GIT_TAG"
           BRANCH="$(git current-branch)"
